#!/bin/bash

echo "🔍 Vérification de l'abonnement avec coupon 0€"
echo "=============================================="
echo ""
echo "✅ CORRECTIONS APPLIQUÉES:"
echo "- create-subscription: Ajout du {CHECKOUT_SESSION_ID} dans success_url"
echo "- check-payment-status: Gestion des montants à 0€ avec coupons" 
echo "- Condition: payment_status === 'paid' OU (amount_total === 0 && status === 'complete')"
echo ""
echo "📋 ÉTAPES DE TEST RECOMMANDÉES:"
echo "1. Aller sur /subscribe sur votre site"
echo "2. Choisir un plan et cliquer 'S'abonner'"
echo "3. Utiliser votre code coupon pour passer à 0€"
echo "4. Compléter le 'paiement'"
echo "5. Vérifier que l'URL contient: ?session_id=cs_xxxx"
echo "6. Observer la vérification automatique du paiement"
echo ""
echo "🎯 RÉSULTAT ATTENDU:"
echo "- URL avec session_id ✓"
echo "- Vérification automatique ✓"  
echo "- Abonnement créé en base ✓"
echo "- Confettis de célébration ✓"
echo ""
echo "⚠️  Si vous ne voyez pas le session_id dans l'URL:"
echo "- Le problème était l'ancienne version de create-subscription"
echo "- Refaites un nouveau test avec la version corrigée"
echo ""
echo "📊 POINTS DE DEBUG:"
echo "- Console du navigateur pour les logs de vérification"
echo "- Dashboard Stripe pour voir les sessions et abonnements"
echo "- Logs Supabase pour voir les appels aux Edge Functions"
