#!/bin/bash

echo "🔗 GUIDE COMPLET - CONFIGURATION WEBHOOKS STRIPE"
echo "================================================"
echo ""

echo "📋 ÉTAPES À SUIVRE :"
echo ""

echo "1️⃣ DÉPLOYER LES EDGE FUNCTIONS SUPABASE"
echo "----------------------------------------"
echo "# Connectez-vous à Supabase (si pas déjà fait)"
echo "supabase login"
echo ""
echo "# Déployez les fonctions"
echo "supabase functions deploy create-subscription"
echo "supabase functions deploy stripe-webhook"
echo ""
echo "# Récupérez l'URL de votre projet"
echo "supabase status"
echo ""

echo "2️⃣ CONFIGURER LE WEBHOOK DANS STRIPE"
echo "-------------------------------------"
echo "🌐 Allez sur : https://dashboard.stripe.com/webhooks"
echo ""
echo "👆 Cliquez sur '+ Add endpoint'"
echo ""
echo "📝 URL de l'endpoint :"
echo "   https://[VOTRE-PROJET-ID].supabase.co/functions/v1/stripe-webhook"
echo "   (Remplacez [VOTRE-PROJET-ID] par votre vrai ID Supabase)"
echo ""
echo "📺 Événements à sélectionner :"
echo "   ✅ checkout.session.completed"
echo "   ✅ customer.subscription.created"
echo "   ✅ customer.subscription.updated" 
echo "   ✅ customer.subscription.deleted"
echo "   ✅ invoice.payment_succeeded"
echo "   ✅ invoice.payment_failed"
echo ""
echo "💾 Cliquez sur 'Add endpoint'"
echo ""

echo "3️⃣ RÉCUPÉRER LE WEBHOOK SECRET"
echo "-------------------------------"
echo "📋 Dans l'endpoint que vous venez de créer :"
echo "   - Cliquez sur l'endpoint"
echo "   - Allez dans 'Signing secret'"
echo "   - Cliquez sur 'Reveal' ou 'Click to reveal'"
echo "   - Copiez la valeur (commence par 'whsec_...')"
echo ""

echo "4️⃣ AJOUTER LES VARIABLES DANS VERCEL"
echo "------------------------------------"
echo "🌐 Allez sur : https://vercel.com/dashboard"
echo "👆 Sélectionnez votre projet Cureliah"
echo "⚙️  Allez dans Settings > Environment Variables"
echo ""
echo "🔑 Ajoutez ces variables :"
echo "   Variable 1:"
echo "     Name: STRIPE_WEBHOOK_SECRET"
echo "     Value: whsec_... (la valeur copiée à l'étape 3)"
echo "     Environment: Production"
echo ""
echo "   Variable 2:"
echo "     Name: STRIPE_SECRET_KEY"
echo "     Value: sk_live_... (votre clé secrète Stripe)"
echo "     Environment: Production"
echo ""
echo "   Variable 3:"
echo "     Name: SUPABASE_SERVICE_ROLE_KEY"
echo "     Value: (votre service role key Supabase)"
echo "     Environment: Production"
echo ""

echo "5️⃣ REDÉPLOYER VOTRE APPLICATION"
echo "--------------------------------"
echo "🔄 Dans Vercel :"
echo "   - Allez dans l'onglet 'Deployments'"
echo "   - Cliquez sur 'Redeploy' sur le dernier déploiement"
echo "   OU"
echo "   - Faites un nouveau push git"
echo ""

echo "6️⃣ TESTER LES WEBHOOKS"
echo "----------------------"
echo "🧪 Dans Stripe Dashboard :"
echo "   - Allez dans votre webhook"
echo "   - Cliquez sur 'Send test webhook'"
echo "   - Sélectionnez 'checkout.session.completed'"
echo "   - Cliquez sur 'Send test webhook'"
echo ""
echo "✅ Vérifiez que le statut est '200' (succès)"
echo ""

echo "🎯 RÉSUMÉ DES URLs IMPORTANTES :"
echo "Stripe Dashboard: https://dashboard.stripe.com/webhooks"
echo "Vercel Dashboard: https://vercel.com/dashboard"
echo "Supabase Dashboard: https://supabase.com/dashboard"
echo ""

echo "📞 En cas de problème :"
echo "   - Vérifiez les logs Supabase : supabase functions logs stripe-webhook"
echo "   - Vérifiez les logs Vercel dans l'onglet 'Functions'"
echo "   - Les webhooks Stripe ont un délai de retry automatique"

echo ""
echo "✨ Une fois terminé, vos paiements Stripe seront entièrement fonctionnels !"
