# Configuration Prometheus pour Cureliah
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Métriques de l'application
  - job_name: 'cureliah-app'
    static_configs:
      - targets: ['cureliah-app:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Métriques Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['cureliah-app:9113']
    scrape_interval: 30s

  # Métriques Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Health checks des services externes
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://cureliah.com
        - https://api.cureliah.com/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
